export * from './bank-account.model'
export * from './contact-info.model'
export * from './customer-info.model'
export * from './holder.model'
export * from './party-service-info.model'
export * from './personal-info.model'
export * from './pod-sso-info.model'
export * from './register-Info.model'